import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header/Header";
import Banner from "../components/Banner/Banner";
import SmallCard from "../components/SmallCard/SmallCard";
import MediumCard from "../components/MediumCard/MediumCard";
import LargeCard from "../components/LargeCard/LargeCard";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export type ExploreData = {
  img: string;
  location: string;
  distance: string;
};

export type CardData = {
  img: string;
  title: string;
};
interface HomeProps {
  exploreData: Array<ExploreData>;
  cardData: Array<CardData>;
}

export default function Home({ exploreData, cardData }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Airnb V.2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold-pb-5"> Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(
              ({ img, location, distance }, i): JSX.Element => (
                <SmallCard
                  key={i}
                  img={img}
                  location={location}
                  distance={distance}
                />
              )
            )}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3">
            {cardData?.map(
              ({ img, title }, i): JSX.Element => (
                <MediumCard img={img} title={title} key={i} />
              )
            )}
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated Airnb"
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );

  const cardData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
      cardData,
    },
  };
}
